### PR TITLE
fixes batch requests for POST

### LINKED ISSUE #736: Request body empty when using batch - V2 beta API
Hi,

When batching Gmail API requests, such as "modify" requests for messages (setting/unsetting labels on messages), I noticed that with v2 beta API, the API returns a 500 server error.

By using some print_r statements in the v2 API source code, I have found that when using batch (Google_Http_Batch) containing POST requests with a body, the request effectively sent does not have any body. However, when NOT using batch calls, everything works fine. Further debugging shows that the request being batched is well constructed, and contains a body.

Having a look at the Google\Http\Batch.php source code (lines 77-81) :       
$body .= sprintf(
          '%s %s HTTP/%s',
          $request->getMethod(),
          $request->getResource(),
          $request->getProtocolVersion()
);

we can see that there's nothing to include the $request body (could be obtained by $request->getBody()).

It tried to figure out how it could be done (by refering to the request being sent by v1 API), with :
      $body .= sprintf(
          '%s %s HTTP/%s %s',
          $request->getMethod(),
          $request->getResource(),
          $request->getProtocolVersion(),
          $request->getBody() ? "\n\n" . $request->getBody():''
);

but I always encounter a 500 server error.

Please, anyone can have a look at this issue ? Thanks

### PR DESCRIPTION
**Pull request by bshaffer**
fixes #736

### CODE REVIEW

File: src/Google/Http/Batch.php [hunk 1]
```diff
@@ -61,26 +61,38 @@ public function execute()
...
-      $body .= "\n\n";
+
+      $content = (string) $request->getBody();
+
+      $body .= sprintf(
+          $batchHttpTemplate,
+          $this->boundary,
+          $key,
+          $firstLine,
+          Request::getHeadersAsString($request),
```
Comment (tmatsuo) [inline src/Google/Http/Batch.php]: Does `Request::getHeadersAsString()` have a newline at the beginning? Otherwise it will be in the same line with the `$firstLine` as far as I read the code.

Comment (bshaffer) [inline src/Google/Http/Batch.php]: Yes it does... it's very counter intuitive, and I don't like it, but it does.

We could also call it with `trim` and then the template could have a new line. I'm not a particular fan of either way.

Comment (tmatsuo) [inline src/Google/Http/Batch.php]: The implementation is:
https://github.com/guzzle/guzzle/blob/5.3/src/Message/AbstractMessage.php#L206

Is it safe to assume they won't change the implementation?

Comment (bshaffer) [inline src/Google/Http/Batch.php]: yeah I think so :D

**Comment by tmatsuo** [comment]
LGTM

File: src/Google/Http/Batch.php (hunk 1 above)
Comment (bshaffer) [inline src/Google/Http/Batch.php]: I understand why they are doing this - if there are no headers, then the first line should still only have one new-line between it and the body, so this prevents an unnecessary newline character if there are no headers.
